### ISSUE TITLE
Document `UI ready schema` so that others can write parsers that conform to it

### ISSUE THREAD

**Issue by quangkhoa** [temando/open-api-renderer#106]
Expected outcome:
- json schema for `UI ready schema`
- docs (optional)

**Comment by brendo** [comment]
🎉   I've created [lincoln-schema-spec](https://github.com/temando/lincoln-schema-spec) which defines the current UI Ready Schema which Lincoln understands.

The schema is loosely defined, and I expect we'll be able to iterate on it several times before we're happy. Nevertheless, it's a start and pays forward to #156!
