### ISSUE TITLE
Support the servers functionality - for url and description

### ISSUE THREAD

**Issue by brendo** [temando/open-api-renderer#157]
Open API allows for [servers](https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc2/versions/3.0.md#serverObject) definition, which our parser currently doesn't handle.

Ideally the UI would also show the server information, currently we don't have anything to indicate what the actual URL of the API is!

**Comment by quangkhoa** [comment]
This ticket is a prerequisite for #160
