### ISSUE TITLE
Degrade gracefully on definitions with circular references

### ISSUE THREAD

**Issue by MikeRalphson** [temando/open-api-renderer#176]
Currently the renderer aborts with the message

> Failed to load definition. too much recursion

Using [topological sorting](https://en.wikipedia.org/wiki/Cycle_(graph_theory)#Cycle_detection) or another algorithm, it should be possible to identify circular `$ref`s and possibly omit those sections of the definition only, allowing the remainder of the definition to be rendered (with warnings?).

**Comment by brendo** [comment]
Do you have a sample definition that we could reproduce with?

Currently the schema dereferencing is outsourced to the [json-schema-ref-parser](https://www.npmjs.com/package/json-schema-ref-parser) project. We have also looked at [jst](https://github.com/jdwije/jst/) as a possible replacement, but encountered some performance issues in doing so.

Nevertheless, we should do better at handling this :)

**Comment by brendo** [comment]
With that said, there may be something on our end too with our `oneOfResolver` or `allOfResolver` that could be causing this issue. We know of degraded performance when there are several `oneOf` permutations in a document and have some ideas to get around this (such as only calculating the first couple).

**Comment by MikeRalphson** [comment]
https://gist.github.com/MikeRalphson/4a0740e1d809ac6b6bf577894ea8a985

I think it's likely the `$ref` in `#/components/schemas/category/sub_categories` to `#/components/schemas/category` in this case rather than the `oneOf`.

BTW great project, very impressive, this is a minor niggle.

**Comment by brendo** [comment]
Hey @MikeRalphson, @quangkhoa has implemented a solution. That [gist renders now](https://temando.github.io/open-api-renderer/demo/?url=https://gist.githubusercontent.com/MikeRalphson/4a0740e1d809ac6b6bf577894ea8a985/raw/dec2be1bc76480c3c5b3c74ee998acdf62f047df/openapi3-circular-refs.yaml)!

**Comment by MikeRalphson** [comment]
Very nice - clear representation!
