### ISSUE TITLE
Fix and extend the OpenAPI V3 validator

### ISSUE THREAD

**Issue by Szasza** [temando/open-api-renderer#196]
Hi Temando Team,

Thank you for sharing Lincoln, happy to chip in with addressing the following:

- Fixing the OpenAPI v3 validator - currently it is broken due to an invalid parameter passing in BaseJS line 103.
- Adding support for sending the definition in a post request instead of sending an URL, which (the latter) doesn't work in case of relative URL-s and non-public schemas.

**Comment by brendo** [comment]
Thanks, look forward to the PR's!
