### ISSUE TITLE
Adding the endpoint to the navigation

### ISSUE THREAD

**Issue by Szasza** [temando/open-api-renderer#199]
Current situation: in the left-hand side navigation all the menu items are listed based on endpoints and request types, but it is the summary which is shown next to the request type.

Example:
`GET A test summary here`

Question: is it an acceptable change to add the endpoint path to the left-hand side nav's menu items and to move the summary into a next line?

Example:
```
GET /some/endpoint
A test summary here
```

If so, I am happy to create a PR.

**Comment by Szasza** [comment]
Note to self: code changes are implemented but waiting for #200 to be checked and merged first to avoid issues.

**Comment by brendo** [comment]
How do you feel about having this behind an option? Having a large API could make the navigation a little unwieldy to navigate, but I agree that sometimes it's easier to just look `POST /pets` than `Add a Pet`

**Comment by Szasza** [comment]
Sure, can do, actually the branch I have for this shows both for one nav item, i.e.
```
POST /pets
Add a pet
```
Happy to make it configurable.
