### ISSUE TITLE
Support commonmark for method description and schema element description

### ISSUE THREAD

**Issue by quangkhoa** [temando/open-api-renderer#21]
**Currently, if a method description is written in markdown, it is rendered as is, e.g.**

![image](https://cloud.githubusercontent.com/assets/9293754/25886904/2152003e-35a3-11e7-9c0b-7d60e80c1ed1.png)

**Ideally it should be rendered as html, e.g.**
![image](https://cloud.githubusercontent.com/assets/9293754/25886961/5e1a8018-35a3-11e7-97c1-0cae25da2463.png)

This also applies to schema element description.

**Comment by brendo** [comment]
Just a note that [Open API v3 spec](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#richText) specifies that CommonMark is the preferred _flavour_ of Markdown to support:

> ### Rich Text Formatting
> Throughout the specification description fields are noted as supporting CommonMark markdown formatting. OpenAPI compliant tooling MUST support [CommonMark 0.27](http://spec.commonmark.org/0.27/).
