### ISSUE TITLE
Add support for multiple Open API files

### ISSUE THREAD

**Issue by quangkhoa** [temando/open-api-renderer#8]
Allow the app to preload a list of Open API files when it renders, e.g. like the following wireframe.

![image](https://cloud.githubusercontent.com/assets/9293754/25888099/2a5f73fa-35a8-11e7-9c93-7d0b4aa47097.png)

Also have a look at [Redoc Demo](https://github.com/Rebilly/ReDoc/blob/master/demo/examples/multiple-apis/index.html)

**Comment by brendo** [comment]
As the project is now exposed as a component, this should be easier to do ;)
