### ISSUE TITLE
Add json visualiser to visualise `examples`

### ISSUE THREAD

**Issue by quangkhoa** [temando/open-api-renderer#9]
Currently the examples are rendered as static text, e.g.

![image](https://cloud.githubusercontent.com/assets/9293754/25887912/62a25fa8-35a7-11e7-9c55-08b9df1559e7.png)

They should be rendered as json, e.g.

![image](https://cloud.githubusercontent.com/assets/9293754/25887994/c1165b7a-35a7-11e7-9463-e074dc8a181f.png)

**Comment by brendo** [comment]
Keep in mind when looking for a library to do this (I wouldn't recommend rolling our own), that is should ideally be able to handle more than just JSON (eg. XML).

So for a mini checklist I'd say:

- Code highlighting should support JSON/XML.
- Code folding is desired (collapse/expand); extra points if you can configure an automatic code fold at a _different level_. For example ReDoc currently starts with only the top level visible. For JSON API responses this is a bit annoying as `data` is the first element and you **always** have to expand it to get any detail. Being able to automatically code fold at the second level would be helpful
- Should support one click copy!
- Line numbers nice to have

**Comment by quangkhoa** [comment]
resolved by #67
