### ISSUE TITLE
Accept initial opened tree depth for schema visualiser

### ISSUE THREAD

**Issue by quangkhoa** [temando/open-api-renderer#96]

**Comment by brendo** [comment]
Looks like this could be supported by default now, https://github.com/mac-s-g/react-json-view/commit/b563502c9a42ec0c89303d101f4d88ef74c9b5c0

**Comment by quangkhoa** [comment]
Thanks @brendo. That link will help the json visualiser. This ticket is about the schema visualiser (-:
